### ISSUE TITLE
New repo for VxKex

### ISSUE THREAD

**Issue by CommonLoon102** [CopperFr/cpc-fractal-tree#1]
https://github.com/i486/VxKex

**Comment by i486** [comment]
@CopperFr 
@CommonLoon102 

Hey guys, some updates on the VxKex situation:

vxiiduu nuked all his accounts, including the GitHub repo, because someone tried to dox him. 
Check out this screenshot:

![vxiiduu](https://github.com/user-attachments/assets/0993deaf-f604-44ff-9861-212da99727e7)

Someone also created this suspicious repo:
https://github.com/VxKex/VxKex

When asked if this was him, vxiiduu said:
![vxiiduu1](https://github.com/user-attachments/assets/2bfe3b9d-b8ad-445c-9d59-86a99797724c)

So, the original project is now officially discontinued/abandoned. 

@CopperFr, this might be the perfect time to create your own repo, since the official project is gone. I really hope you're not abandoning the project too.

Also, it's pretty concerning that someone's pretending to be vxiiduu and planning to release "VxKex 2.0".

https://github.com/i486/VxKex
As for this repo, or now, I've set up this for my own archival, issue collection, and maybe support for other VxKex users if no one else steps up.

If you really, really don't want to create your own repo, @CopperFr, I'm up for fixing https://github.com/i486/VxKex a bit, and you can continue there as usual.

What do you guys think? How should we move forward with this?

**Comment by CommonLoon102** [comment]
The impersonator guy cannot use git either, since the repo is empty and the source is attached as a 7z file. 
I'd suggest to just ignore him.

Someone has already set up mirroring for the i486/VxKex GitHub repo to a privately hosted Gitea repo.

@CopperFr could fork i486/VxKex and from there he could open PRs to i486/VxKex is he wants to.

Someone might implement GitHub CI/CD in the future to build the binaries automatically via GitHub.

**Comment by CommonLoon102** [comment]
@CopperFr could you please share the source code for your changes? If you don't want to fork and create PRs, then it's OK even if it is just in a zip file, we can compare manually. Then others can take over and maintain the project. Contributions would be easier after that.
